version: '3'
services:
  web:
    build:
      context: .
    command: >
      sh -c "uvicorn app.main:app"
    volumes:
      - .:/usr/src
    ports:
      - "8080:8080"
    env_file: "environment.env"